FROM mhart/alpine-node
WORKDIR /hexo

RUN npm install hexo-cli -g && \
    hexo init . && \
    npm install && \
    rm -rf /tmp/*

VOLUME ["/hexo/source", \
        "/hexo/themes", \
        "/hexo/public"]

EXPOSE 4000
CMD ["hexo", "g"]
